vim.cmd "highlight StatusType guibg=#000000 guifg=#5eacd3"
vim.cmd "highlight StatusFile guibg=#000000 guifg=#ffffff"
vim.cmd "highlight StatusModified guibg=#000000 guifg=#d3869b"
vim.cmd "highlight StatusBuffer guibg=#000000 guifg=#1d2021"
vim.cmd "highlight StatusLocation guibg=#000000 guifg=#5eacd3"
vim.cmd "highlight StatusPercent guibg=#000000 guifg=#ebdbb2"
vim.cmd "highlight StatusNorm guibg=#000000 guifg=none"
vim.o.statusline = " "
                                .. "%#StatusType#"
                                .. ""
                                .. "<< "
                                .. "%Y"
                                .. ""
                                .. " >>"
                                .. ""
                                .. "%#StatusFile#"
                                .. "  "
                                .. "%F"
                                .. " "
                                .. "%#StatusModified#"
                                .. " "
                                .. "%m"
                                .. " "
                                .. "%#StatusNorm#"
                                .. "%="
                                .. "%#StatusLocation#"
                                .. "<< "
                                .. "%l,%c"
                                .. " >>"
                                .. "%#StatusPercent#"
                                .. " "
                                .. "%p%%"
                                .. " "
